### PR TITLE
Wasm 2.0 Update

### PR DESCRIPTION
**Pull request by raoxiaojia**
This PR is created for visibility of the in-progress update to Wasm 2.0+, the current version of spec displayed on the [spec webpage](https://webassembly.github.io/spec/core/), with additional subtyping implementation from the [future proposals](https://webassembly.github.io/gc/core/).

# Release 2.0 + Subtyping

This release for Wasm 2.0 + Subtyping implemented the following changes in the official spec release 2.0:
- Multiple-value blocks;
- Reference types;
- Table instructions;
- Multiple tables;
- Bulk memory and table instructions.

In addition, this release also implemented the subtyping system from the future funcref/GC proposals.

The new sign extension, non-trapping float-to-int conversion, and vector types are added but without any concrete implementation.

## Updated Components:
- [x] Base opsem/typing definitions;
- [x] Preservation theorems;
- [x] Interpreter and progress theorem;
- [x] Instantiation;
- [x] Instantiation soundness theorems;
- [x] Type checker;
- [x] Type checker correctness theorem;
- [x] Binary printer/parser;
- [x] Code pretty printer;
- [x] Subtyping.

# Major Structural Changes

## Values vs Instructions
Due to the introduction of reference values, values are no longer necessarily basic instructions; function references and external references are expressed as administrative instructions due to their direct usage of store addresses instead of module indices. This change has broken some assumptions that many original proofs and definitions based on -- mostly those related to value typing (see below). 
Total and partial conversion operations are now provided for conversion between values and their corresponding instructions:
- `v_to_e/e_to_v` for total conversions;
- `e_to_v_opt` for partial operations.

## Value Typing and the Store
Due to the use of store addresses, the new reference values can only be typed given a store. This necessitated the introduction
of a separate `value_typing` relation with respect to a store. In addition, value typing relation now has to be done at the
`e_typing` level (for administrative instructions) as they can no longer be converted to basic instructions and typed using the `const` rule in `be_typing`. New value typing inversion lemmas were added to help reasoning with this change; search for terms involving `value_typing` and `values_typing`.

## Threads
Threads are now properly spelt out as a separate type that constitutes the configuration tuple. The old thread-related definitions (e.g. `s_typing`) are renamed to the names used in the standard (e.g. `thread_typing`).

## Type System and Subtyping
In addition, this release also implements subtyping introduced in the future funcret/GC proposal as a forward-looking move. There is currently no observable effect in Wasm 2.0 except for typing instructions past unconditional branches, as there is no non-trivial subtypings between any of the base value types. There exists a principal type (potentially with some free type parameters) for every value/instruction, which all possible types of it are supertypes of.
The largest impact of this type system change is that, in the future, values can no longer uniquely typed even if it is well typed. This is not the case in Wasm 2.0 yet, but examples can be introduced in future proposals.
The old `weakening` typing rules are replaced by a subtyping rule as a result of this change, which reflects the shift in the future proposals.

# Refactorings and Feature Improvements

## Host Formulation
The parametric host language is now defined using typeclasses. 
The main major benefit is the automatic filling of implicit host parameter, instead of needing to redefine all operations involving anything downstream from function instances and stores. The proof context is also greatly simplified since all these redefinitions no longer exist to occupy a major chunk of the buffer window.

## Numerics
- Refactored the old collection of conversion operations *cvtop* to be split up by their individual constructors to better match the spec.

## Name Changes
- Changed the name of some types, instructions, and constructors to better match the official spec.
- Instance indices are now simplified to the base `u32` type without additional constructors.

## Pretty Printer
- Implemented pretty printing for conversion operations.

## Typing
- Massively improved the scope and automation of the typing inversion lemmas.
- Provided a new tactic `resolve_e_typing` that automatically tries to resolve `e_typing` goals, dealing mostly with the operands.
- Provided a separate file for the new subtyping lemmas and tactics.

## Type Checker
- Completely reimplemented the type checker, which should now be slightly more efficient (although this should hardly be observable).

## Miscellaneous
- Introduced many additional excerpts in comments from the official spec for various definitions.

# Bug Fixes
- Fixed a bug where the binary printer incorrectly prints all types of reinterpret conversions to 0xBC.
- Fixed a bug where the binary printer sometimes prints indices via a conversion to nat first.

### CODE REVIEW

**Comment by womeier** [comment]
Thanks for the detailed description of the upcoming changes! This is very helpful for us.

**Comment by womeier** [comment]
I'm currently working on the proof that the Wasm module we generate instantiates.
Since you made some changes to the instantiation_spec, I'd like to update to a version of your 2.0 branch as soon as possible. (it's ok if it doesn't have tail calls)

How stable is the current instantiation_spec file, do you expect significant changes?
(Also, the current version doesn't seem to compile.)

**Comment by raoxiaojia** [comment]
> I'm currently working on the proof that the Wasm module we generate instantiates. Since you made some changes to the instantiation_spec, I'd like to update to a version of your 2.0 branch as soon as possible. (it's ok if it doesn't have tail calls)
> 
> How stable is the current instantiation_spec file, do you expect significant changes? (Also, the current version doesn't seem to compile.)
> 
> thanks!

I'm hoping the definitions should be pretty stable, although proofs down that line haven't been updated, so there might be some mistakes. I'm guessing your line of work doesn't depend on the instantiation soundness proofs, so at least you could try to incorporate the current definition and see if it works with your modules (and potentially find some mistakes before I find them during the proofs)!

Note that in 2.0 the table/memory initialisations are now separated to execution of a series of the new table/memory operations, while it was initially hardcoded in the mechanised 1.0, so the 'real' final instantiation store is the store post-execution of those instructions.

**Comment by womeier** [comment]
> 
> I'm hoping the definitions should be pretty stable, although proofs down that line haven't been updated, so there might be some mistakes. I'm guessing your line of work doesn't depend on the instantiation soundness proofs, so at least you could try to incorporate the current definition and see if it works with your modules (and potentially find some mistakes before I find them during the proofs)!

Yes, I'll do that, thanks! I'll report if I notice anything.

> 
> Note that in 2.0 the table/memory initialisations are now separated to execution of a series of the new table/memory operations, while it was initially hardcoded in the mechanised 1.0, so the 'real' final instantiation store is the store post-execution of those instructions.
> 
> I'm also hoping that all files compile except the type checker and instantiation proofs now -- let me know if that is not what you see on your side.


It works, the project compiles after deleting (for now) the said files and the ones depending on them.

**Comment by raoxiaojia** [comment]
> > I'm hoping the definitions should be pretty stable, although proofs down that line haven't been updated, so there might be some mistakes. I'm guessing your line of work doesn't depend on the instantiation soundness proofs, so at least you could try to incorporate the current definition and see if it works with your modules (and potentially find some mistakes before I find them during the proofs)!
> 
> Yes, I'll do that, thanks! I'll report if I notice anything.
> 
> > Note that in 2.0 the table/memory initialisations are now separated to execution of a series of the new table/memory operations, while it was initially hardcoded in the mechanised 1.0, so the 'real' final instantiation store is the store post-execution of those instructions.
> > I'm also hoping that all files compile except the type checker and instantiation proofs now -- let me know if that is not what you see on your side.
> 
> It works, the project compiles after deleting (for now) the said files and the ones depending on them.

A quick status update -- it seems that there's a new introduction of a real bottom type in the 2.0 spec which has been missed in the update so far. I've only discovered this earlier when I find that there was seemingly a problem with typing certain polymorphic instructions (select, in particular). After talking to Andreas, it seems that the best approach is to implement the real bottom type with the correct subtyping, (quote from Andreas: ...which essentially is what the funcref/GC proposal does). 

   I may take some time to see what the GC proposal does and implement this part faithfully, but I'll need to talk to Conrad first to have a discussion on the best approach. On the upside, a correct decision here should make it easier when you implement the full GC proposal for your work, if you're to try it at some point.

   This is quite a large change in the fundamental type system as it adds a new constructor to the base value type, but I don't think it will have too much impact on you, since most of the impact of this change should have been absorbed along the way in various definitions. But I thought it's useful for you to be aware of this change ahead.

**Comment by raoxiaojia** [comment]
Just another status update on subtyping -- I went through some lengthy email discussions with Andreas and Conrad regarding certain subtyping rules throughout the last week; in the end we decided that it is the best if I directly implement the genuine subtyping system in the GC proposal (but without introducing those new types), instead of the temporary method in 2.0. We've discussed about fixing some rules in the proposal as well during the discussion.

The subtyping implementation proved to require a huge restructuring of the type system and how certain typing rules work, due to types of many more items no longer being unique (although a principal type/typing scheme does exist for all objects), and many type signatures that originally need to be equal are now only required to be related by subtyping (sensible). I now almost have all the proofs recovered. Hopefully this proves to be the last obstacle in this update!

I'll update the changelog (and the introduction here) at some point tomorrow. In the mean time, if you want to get a rough idea of what to expect before my changelog, you can browse the subtyping branch (https://github.com/raoxiaojia/WasmCert-Coq/tree/subtyping).

**Comment by womeier** [comment]
thanks for the update! CC @opqrs @spitters

**Comment by raoxiaojia** [comment]
Update: This is finally done! Subtyping proved to be require a lot of overhauls in some existing proof structures (together with the basically reimplemented version of type checker).

More clean-ups may come in the next few days, but otherwise this should be merged at the end of this week unless anything else comes up.

**Pull request merged**
