### PR TITLE
fix dune setup

### PR DESCRIPTION
**Pull request by womeier**
As discussed in #9 :

- only the Wasm library, removed the interpreter for now
- ~~inlined stronginduction~~ replaced stronginduction with well-founded induction from standard lib
- updated to Coq 8.14 (doesn't yet work with 8.15)
- removed esy files
- gh actions: https://github.com/womeier/WasmCert-Coq/actions/runs/5596373595/jobs/10233310029

### CODE REVIEW

**Comment by Mbodin** [comment]
I failed to compile on my computer: the dependencies failed to install. Can you provide a lockfile with the exact version of all dependencies? Thanks in advance!

**Comment by womeier** [comment]
you can check the dependencies before https://github.com/WasmCert/WasmCert-Coq/pull/24/commits/30af82c931d22b0adc3884093a060c2ef55a172c

or look at the GH actions job, it also prints the versions of the dependencies

**Comment by spitters** [comment]
@womeier Quick comment on the use of strong induction:
https://coq-club.inria.narkive.com/VWS50VZQ/adding-strong-induction-to-the-standard-library

**Comment by Mbodin** [comment]
> or look at the GH actions job, it also prints the versions of the dependencies
Indeed: https://github.com/womeier/WasmCert-Coq/actions/runs/5561108003/jobs/10158558539#step:4:580

I wasn't using the same version of OCaml, so I setted up a switch pinning these exact versions of dependencies.

I unfortunately get the exact same error: Opam fails to install Coq 8.14.1. I tried with the commands stated in the Github workflow, but also manually:
```bash
$ opam list
# Packages matching: installed
# Name                   # Installed # Synopsis
base-bigarray            base
base-threads             base
base-unix                base
conf-findutils           1           Virtual package relying on findutils
conf-g++                 1.0         Virtual package relying on the g++ compiler (for C++)
conf-gmp                 4           Virtual package relying on a GMP lib system installation
dune                     3.9.1       Fast, portable, and opinionated build system
menhir                   20230608    An LR(1) parser generator
menhirLib                20230608    Runtime support library for parsers generated by Menhir
menhirSdk                20230608    Compile-time library for auxiliary tools related to Menhir
ocaml                    4.07.1      The OCaml compiler (virtual package)
ocaml-base-compiler      4.07.1      Official release 4.07.1
ocaml-config             1           OCaml Switch Configuration
ocaml-secondary-compiler 4.08.1-1    OCaml 4.08.1 Secondary Switch Compiler
ocamlbuild               0.14.2      OCamlbuild is a build system with builtin rules to easily build most OCaml projects
ocamlfind                1.9.6       A library manager for OCaml
ocamlfind-secondary      1.9.6       Adds support for ocaml-secondary-compiler to ocamlfind
zarith                   1.12        Implements arithmetic and logical operations over arbitrary-precision integers
$ opam install coq.8.14.1
The following actions will be performed:
  ∗ install coq 8.14.1

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved coq.8.14.1  (cached)
[ERROR] The compilation of coq.8.14.1 failed at "make COQ_USE_DUNE= -j4".

#=== ERROR while compiling coq.8.14.1 =========================================#
# context     2.1.0 | linux/x86_64 | ocaml-base-compiler.4.07.1 | https://opam.ocaml.org/#aa4ff8bc
# path        ~/.opam/4.07.1/.opam-switch/build/coq.8.14.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build make COQ_USE_DUNE= -j4
# exit-code   2
# env-file    ~/.opam/log/coq-8571-5f3ae6.env
# output-file ~/.opam/log/coq-8571-5f3ae6.out
### output ###
# [...]
# Makefile.common:189: recipe for target '_build/default/user-contrib/Ltac2/ltac2_plugin.cmxs' failed
# make[1]: *** [_build/default/user-contrib/Ltac2/ltac2_plugin.cmxs] Error 1
# make[1]: *** Waiting for unfinished jobs....
# Warning: Coq Language Versions lower than 0.8 have been deprecated in Dune
# 3.8 and will be removed in an upcoming Dune version.
# Warning: Coq Language Versions lower than 0.8 have been deprecated in Dune
# 3.8 and will be removed in an upcoming Dune version.
# Warning: Coq Language Versions lower than 0.8 have been deprecated in Dune
# 3.8 and will be removed in an upcoming Dune version.
# make[1]: Leaving directory '/scratch/mbodin/.opam/4.07.1/.opam-switch/build/coq.8.14.1'
# Makefile.make:122: recipe for target 'submake' failed
# make: *** [submake] Error 2



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build coq 8.14.1
└─ 
╶─ No changes have been performed
```

I'm sorry: it's not your fault, but somehow this version of Coq doesn't compile on my computer as-is using Opam. I should probably report it somewhere.

I just tested with `esy`: I do get the same compilation error with this version of Coq ☹

**Comment by spitters** [comment]
@Mbodin maybe https://coq.zulipchat.com/#narrow/stream/240550-Dune-devs-.26-users

**Comment by spitters** [comment]
@Mbodin One possibility may be that part of your installation comes from your OS package manager and part from opam. Opam prefers to install everything by itself.

**Comment by womeier** [comment]
FYI:     OCaml 4.07 is just the version in the CI

I use OCaml 4.12 (and 4.13 also works), so I don't think it's the OCaml version.

**Comment by womeier** [comment]
hey @Mbodin, is there anything I can do to make this progress?

btw, I personally don't need the interpreter and would be very happy with just the Wasm formalization being
available through opam.

**Comment by raoxiaojia** [comment]
> hey @Mbodin, is there anything I can do to make this progress?
> 
> btw, I personally don't need the interpreter and would be very happy with just the Wasm formalization being available through opam.

I should follow up on this! I'm travelling but should be able to test your opam build soon. If I read correctly the only item missing is the interpreter -- we currently have another branch working on a slightly different version of certified interpreters/instantiation dropping itree temporarily (and slightly more efficient); hopefully it shouldn't take too long for me to figure out how to make it work with the opam build you provided. If not, then a build without the interpreters should be very beneficial as well.

Thanks a lot for your input on this! Having a separate opam build is something I'd liked as well for quite a while.

**Comment by raoxiaojia** [comment]
> > or look at the GH actions job, it also prints the versions of the dependencies
> > Indeed: https://github.com/womeier/WasmCert-Coq/actions/runs/5561108003/jobs/10158558539#step:4:580
> 
> I wasn't using the same version of OCaml, so I setted up a switch pinning these exact versions of dependencies.
> 
> I unfortunately get the exact same error: Opam fails to install Coq 8.14.1. I tried with the commands stated in the Github workflow, but also manually:
> 
> ```shell
> $ opam list
> # Packages matching: installed
> # Name                   # Installed # Synopsis
> base-bigarray            base
> base-threads             base
> base-unix                base
> conf-findutils           1           Virtual package relying on findutils
> conf-g++                 1.0         Virtual package relying on the g++ compiler (for C++)
> conf-gmp                 4           Virtual package relying on a GMP lib system installation
> dune                     3.9.1       Fast, portable, and opinionated build system
> menhir                   20230608    An LR(1) parser generator
> menhirLib                20230608    Runtime support library for parsers generated by Menhir
> menhirSdk                20230608    Compile-time library for auxiliary tools related to Menhir
> ocaml                    4.07.1      The OCaml compiler (virtual package)
> ocaml-base-compiler      4.07.1      Official release 4.07.1
> ocaml-config             1           OCaml Switch Configuration
> ocaml-secondary-compiler 4.08.1-1    OCaml 4.08.1 Secondary Switch Compiler
> ocamlbuild               0.14.2      OCamlbuild is a build system with builtin rules to easily build most OCaml projects
> ocamlfind                1.9.6       A library manager for OCaml
> ocamlfind-secondary      1.9.6       Adds support for ocaml-secondary-compiler to ocamlfind
> zarith                   1.12        Implements arithmetic and logical operations over arbitrary-precision integers
> $ opam install coq.8.14.1
> The following actions will be performed:
>   ∗ install coq 8.14.1
> 
> <><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> ⬇ retrieved coq.8.14.1  (cached)
> [ERROR] The compilation of coq.8.14.1 failed at "make COQ_USE_DUNE= -j4".
> 
> #=== ERROR while compiling coq.8.14.1 =========================================#
> # context     2.1.0 | linux/x86_64 | ocaml-base-compiler.4.07.1 | https://opam.ocaml.org/#aa4ff8bc
> # path        ~/.opam/4.07.1/.opam-switch/build/coq.8.14.1
> # command     ~/.opam/opam-init/hooks/sandbox.sh build make COQ_USE_DUNE= -j4
> # exit-code   2
> # env-file    ~/.opam/log/coq-8571-5f3ae6.env
> # output-file ~/.opam/log/coq-8571-5f3ae6.out
> ### output ###
> # [...]
> # Makefile.common:189: recipe for target '_build/default/user-contrib/Ltac2/ltac2_plugin.cmxs' failed
> # make[1]: *** [_build/default/user-contrib/Ltac2/ltac2_plugin.cmxs] Error 1
> # make[1]: *** Waiting for unfinished jobs....
> # Warning: Coq Language Versions lower than 0.8 have been deprecated in Dune
> # 3.8 and will be removed in an upcoming Dune version.
> # Warning: Coq Language Versions lower than 0.8 have been deprecated in Dune
> # 3.8 and will be removed in an upcoming Dune version.
> # Warning: Coq Language Versions lower than 0.8 have been deprecated in Dune
> # 3.8 and will be removed in an upcoming Dune version.
> # make[1]: Leaving directory '/scratch/mbodin/.opam/4.07.1/.opam-switch/build/coq.8.14.1'
> # Makefile.make:122: recipe for target 'submake' failed
> # make: *** [submake] Error 2
> 
> 
> 
> <><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> ┌─ The following actions failed
> │ λ build coq 8.14.1
> └─ 
> ╶─ No changes have been performed
> ```
> 
> I'm sorry: it's not your fault, but somehow this version of Coq doesn't compile on my computer as-is using Opam. I should probably report it somewhere.
> 
> I just tested with `esy`: I do get the same compilation error with this version of Coq ☹

Hmm, I'm actually getting exactly the same error at failing to install coq@8.14.1 via opam as well in this build :(. I've found this https://github.com/coq/coq/issues/15384 after some searches, from which it seems that using a more recent version of Coq (maybe I should try 8.17 since it's the most recent anyway?) might work.

The question now is, would a build on a more recent version be useful for your side as well?

**Comment by womeier** [comment]
Thanks for looking into it!

For me, updating to Coq version 8.16.1 should be possible, so that would help. (I cannot update to 8.17 yet, but will be able to at some point)

**Comment by spitters** [comment]
@womeier which dependency is blocking the update to 8.17 ?

**Comment by raoxiaojia** [comment]
> Thanks for looking into it!
> 
> For me, updating to Coq version 8.16.1 should be possible, so that would help. (I cannot update to 8.17 yet, but will be able to at some point)

I changed the version of Coq to `>=8.15` and has successfully compiled the codebase with Coq.8.17.1; I haven't tested with lower versions though. But from the issue I've linked above, the bug of Coq installation failure seems to be for 8.14.0/8.14.1 specifically, and is no longer happen for versions >=8.15, so I presume there would be no issue for 8.16.

I'll be trying to integrate the interpreter in as well; hopefully it isn't too difficult.

**Comment by womeier** [comment]
> @womeier which dependency is blocking the update to 8.17 ?

CertiCoq is still on 8.16

**Comment by raoxiaojia** [comment]
> > @womeier which dependency is blocking the update to 8.17 ?
> 
> CertiCoq is still on 8.16

I'll be working with 8.16.1 on the opam branch then -- doesn't seem to differ too much from 8.17 for this project at least, it seems.

**Comment by womeier** [comment]
I just updated to Coq 8.16 and the `opam-interpreter-8.16` branch, everything seems so work from my perspective.
Thanks a lot for the update!

**Comment by raoxiaojia** [comment]
Bumped to 8.17 and testing now. 
Will push and merge this to master at the end of today. That's a goodbye to esy as the default installation method, I guess.

**Comment by opqrs** [comment]
@womeier It would be worth updating the README's installation instructions.

**Comment by raoxiaojia** [comment]
> @womeier It would be worth updating the README's installation instructions.

I’ve updated it under the 8.17 branch — although I’ve not verified if they work from fresh.

**Comment by raoxiaojia** [comment]
Actually, it might give better credit if I merge this PR and then merge #26 separately (which should be easily done since all the 4 commits are already part of #26).

**Comment by spitters** [comment]
What's the status of wasm-cert CI? 
Is it in the central opam directory? Coq platform? In Coq CI? Iris CI? Coq Dune Universe?

I'm not entirely sure which ones are most appropriate, but putting it in such places really helps to avoid breakage.

**Comment by raoxiaojia** [comment]
> What's the status of wasm-cert CI? Is it in the central opam directory? Coq platform? In Coq CI? Iris CI? Coq Dune Universe?
> 
> I'm not entirely sure which ones are most appropriate, but putting it in such places really helps to avoid breakage.

It's in neither of those places yet -- I'm planning to make an opam publish when I've fully updates and tested the readme, which means it will be in the opam directory I guess (and then installable via `opam install wasm_coq` or something). Let me know if you think the other options are more sensible!

**Comment by spitters** [comment]
@raoxiaojia thanks for merging this. Should we create an issue about CI/Opam/platform/... just to be sure it does not get lost.
I see it's still missing here.
https://github.com/coq/opam/tree/master/released/packages

Meanwhile, I've sent a PR to awesome Coq... https://github.com/coq-community/awesome-coq/pull/39

**Comment by raoxiaojia** [comment]
> @raoxiaojia thanks for merging this. Should we create an issue about CI/Opam/platform/... just to be sure it does not get lost. I see it's still missing here. https://github.com/coq/opam/tree/master/released/packages
> 
> Meanwhile, I've sent a PR to awesome Coq... [coq-community/awesome-coq#39](https://github.com/coq-community/awesome-coq/pull/39)

Yes thanks for the reminder! I tried to submit to the main opam repo instead of the coq repo earlier this month, and obviously that couldn't work since all the Coq dependencies are missing, and I haven't switched my mind back on this since then -- will do it now!

**Comment by raoxiaojia** [comment]
https://github.com/coq/opam/pull/2795

Submitted a PR as well.

**Comment by raoxiaojia** [comment]
> @raoxiaojia want to answer this?
> [coq-community/awesome-coq#39](https://github.com/coq-community/awesome-coq/pull/39)

Made a reply! I guess in the end it's up to their maintainer's opinion if they are reluctant to add this at the current stage.

**Pull request merged**
